-- Migration: Add RegulatoryRadar columns to existing risks table
-- These columns support autonomous regulatory scanning via TinyFish Web Agent API

ALTER TABLE public.risks
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS regulation text,
  ADD COLUMN IF NOT EXISTS affected_framework text,
  ADD COLUMN IF NOT EXISTS recommended_action text,
  ADD COLUMN IF NOT EXISTS auto_generated boolean DEFAULT false;

-- Index for filtering auto-generated regulatory alerts
CREATE INDEX IF NOT EXISTS idx_risks_auto_generated ON public.risks (auto_generated) WHERE auto_generated = true;

-- Index for filtering by source
CREATE INDEX IF NOT EXISTS idx_risks_source ON public.risks (source) WHERE source IS NOT NULL;

COMMENT ON COLUMN public.risks.source IS 'Regulatory source (e.g., EUR-Lex, EU AI Office, NIST, NYC.gov)';
COMMENT ON COLUMN public.risks.regulation IS 'Specific regulation reference (e.g., EU AI Act Article 6)';
COMMENT ON COLUMN public.risks.affected_framework IS 'Compliance framework affected (e.g., GDPR, EU AI Act, NIST AI RMF)';
COMMENT ON COLUMN public.risks.recommended_action IS 'LLM-generated recommended remediation action';
COMMENT ON COLUMN public.risks.auto_generated IS 'Whether this risk was auto-generated by RegulatoryRadar';
